### ISSUE TITLE
Storage Information of regex and containers: key error

### ISSUE THREAD

**Issue by lays147** [lays147/YouShallContain#3]
To add a new entry in the storage.local I need a variable name to point to that entry, otherwise, if I repeat the key, the data will be overwritten.
https://github.com/lays147/YouShallContain/blob/work/js/popup.js#L38
Here you will have the key 'register' added to the storage, so if every time I launch the event, the data will be overrated on the 'register' entry.
I need a way to implement 'register' dynamically.

**Comment by mudlabs-monster** [comment]
I don't think you can use dynamically implemented variables here.

The `.set()` method only takes an object literal or named, like you have already. If you try to create it dynamically `.set()` will just set it to whatever your placeholder(code) is. Which will be the same each time, and so overwrite `register`.

- `.set()` does except a callback. But that is no good here as the object will have been overwritten by the time it's triggered

I think you'll need to turn `register` into a multidimensional object.

- When `youShallContain(...)` is called search the storage for the `register` object.
- If _found_ set a new nested object and update (rewrite) `register` with the new version.
- If _not found_ create the `register` object and `.set()`

This way register is still being overwritten each time, but it's acting like an update instead of a reset.

I've sent though a `pull request` with an updated version of `youShallContain(...)`. This version sets the `data.container` value as the nested objects `key` and `data.regex` as its value.

**Comment by lays147** [comment]
The PR #5 Solves this.
